# Generated by Django 5.0.4 on 2024-08-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediafile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediafile',
            name='core_mediaf_descrip_881dc0_idx',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file'], name='core_mediaf_file_8fdacc_idx'),
        ),
    ]
