# Generated by Django 5.0.4 on 2024-08-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_mediafile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mime_type",
                    models.CharField(
                        choices=[
                            ("audio/mpeg", "MP3"),
                            ("audio/wav", "WAV"),
                            ("audio/aac", "AAC"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration", models.DurationField()),
                ("bitrate", models.IntegerField()),
                ("sample_rate", models.IntegerField()),
                ("channels", models.IntegerField()),
                ("genre", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mime_type",
                    models.CharField(
                        choices=[
                            ("image/jpeg", "JPEG"),
                            ("image/png", "PNG"),
                            ("image/gif", "GIF"),
                        ],
                        max_length=50,
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("color_depth", models.IntegerField()),
                ("resolution", models.CharField(max_length=50)),
                ("exif_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mime_type",
                    models.CharField(
                        choices=[
                            ("video/mp4", "MP4"),
                            ("video/avi", "AVI"),
                            ("video/mkv", "MKV"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration", models.DurationField()),
                ("resolution", models.CharField(max_length=50)),
                ("frame_rate", models.FloatField()),
                ("video_codec", models.CharField(max_length=50)),
                ("audio_codec", models.CharField(max_length=50)),
                ("bitrate", models.IntegerField()),
                ("genre", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MediaFile",
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(fields=["file"], name="core_audiof_file_6afaaf_idx"),
        ),
        migrations.AddIndex(
            model_name="imagefile",
            index=models.Index(fields=["file"], name="core_imagef_file_3115d3_idx"),
        ),
        migrations.AddIndex(
            model_name="videofile",
            index=models.Index(fields=["file"], name="core_videof_file_79f000_idx"),
        ),
    ]
