# Generated by Django 5.0.4 on 2024-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_audiofile_imagefile_videofile_delete_mediafile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="bitrate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="channels",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="sample_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="color_depth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="resolution",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="audio_codec",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="bitrate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="frame_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="resolution",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="video_codec",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
