# Generated by Django 5.0.4 on 2024-08-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_audiofile_bitrate_alter_audiofile_channels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="thumbnail_file",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
